name: github action

on: 
  push:
    branches: 
      - main
      
  pull_request:
    branches: 
      - main
jobs:
  test-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: install JDK
        uses: actions/setup-java@v5.0.0
        with: 
          java-version: 17
          distribution: 'temurin'

         
      - name: run spring project
        run: mvn spring-boot:run


        
      
      
    
